[package]
name = "keylined"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
keylined-core = { path = "../keylined-core" }
keylined-config = { path = "../keylined-config" }
keylined-ui = { path = "../keylined-ui" }
keylined-commands = { path = "../keylined-commands" }

tokio.workspace = true
log.workspace = true
env_logger.workspace = true

[dev-dependencies]
test-case.workspace = true
mockall.workspace = true
